[pytest]
# ====================
# SYSTEM CONFIGURATION
# ====================
# Ustawienie pluginu `pytest-bdd`. Mówi mu, gdzie domyślnie szukać plików `.feature`, żebyś w każdym pliku step-defów nie musiał podawać pełnej ścieżki względnej.
bdd_features_base_dir = tests/features
# Używane, gdy ma się nietypową ścieżkę projektu. Sprawia, że gdy odpalisz gołe `pytest` (bez argumentów), użyje relatywnej ścieżki `tests` zamiast pełnej ścieżki katalogu roboczego — a `tests` nie zawiera nawiasów, więc problem znika. To samo osiągniesz, jawnie wołając `pytest tests`.
testpaths = tests
# Włącza w logach wyświetlanie kroków BDD. `adopts` dokleja te flagi do każdego uruchomienia `pytest`.
addopts = --gherkin-terminal-reporter -vv
# Dodaje katalog główny repo do ścieżki importów Pythona. Dzięki temu `from src.pages.home_page import HomePage` działa bez błędu `ModuleNotFoundError`.
pythonpath = .
# ===================
# TESTS CONFIGURATION
# ===================
base_url = https://automationteststore.com/